name: azcore-scheduled

on:
  schedule:
      # Note: the TestAccKeyVaultTs_CLI test needs to run every so often so that the Azure refresh
      # token stored in the GH secret AZURE_CLI_FOLDER doesn't expire. The exact expiration time
      # of the token is not published.
    - cron: '15 3/12 * * *' # 3:15 am and 3:15 pm UTC, every day
  workflow_dispatch: {}

jobs:
  version:
    uses: ./.github/workflows/version.yml
    secrets: inherit

  build_test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    needs: version
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.version.outputs.version }}
      short_test: false
      retention_days: 7
      use_autorest: false
      use_legacy_auth: false
